import sqlite3
con=sqlite3.connect("project.db")
cur=con.cursor()
cur.execute("drop table student_list")
cur.execute("drop table PROFILE")
#cur.execute("drop table ASSIGNMENT_ADMIN")
#cur.execute("drop table PROJECT_ADMIN")
#cur.execute("drop table ATTENDENCE")
cur.execute("drop table staff")
#cur.execute("drop table admin")
cur.execute("PRAGMA FOREIGN_KEYS=ON")
cur.execute("create table student_list(ROLL_NO VARCHAR(10) PRIMARY KEY,NAME TEXT,YEAR VARCHAR,BRANCH VARCHAR(10),PASSWORD VARCHAR(8),SECTION VARCHAR,TRACK VARCHAR(20))")
cur.execute("create table PROFILE(ROLL_NO VARCHAR REFERENCES student_list(ROLL_NO),EMAIL_ID VARCHAR(50),GENDER CHAR,PHONE_NO INT)")
cur.execute("create table staff(staff_id varchar(10),name varchar,email_id varchar,phone varchar,password varchar,track varchar)")
#cur.execute("create table admin(admin_id int,password char)")
#cur.execute("create table ASSIGNMENT_CLIENT(ROLL_NO VARCHAR PRIMARY KEY,DATE VARCHAR,MARKS_OBTAINED FLOAT,TOTAL_MARKS FLOAT,COMPLETED_DATE VARCHAR)")
#cur.execute("create table ASSIGNMENT_ADMIN(ASSIGNMENT_ID INT PRIMARY KEY,DATE VARCHAR,COURSE CHAR,TOPIC CHAR,ASSIGNMENT_QUESTION TEXT,MAX_MARKS FLOAT,DATE_OF_SUBMISSION VARCHAR)")
#cur.execute("create table PROJECT_ADMIN(PROJECT_ID INT PRIMARY KEY,DATE VARCHAR,COURSE CHAR,TOPIC CHAR,ASSIGNMENT_QUESTION TEXT,MAX_MARKS FLOAT,DATE_OF_SUBMISSION VARCHAR)")
#cur.execute("create table ATTENDENCE(ROLL_NO VARCHAR REFERENCES student_list(ROLL_NO),DATE VARCHAR PRIMARY KEY,TOTAL_NO_OF_DAYS INT,DAYS_PRESENT INT,WARNING INT)")
con.commit()
con.close()
